- hosts: all
  become: true
  tasks:
  - name: "update ubuntu package and install apache"
    apt:
      name: apache2
      state: present
      update_cache: true
  - name: run apache
    service:
      name: apache2
      state: started
      enabled: yes
- hosts: vm2
  become: true
  tasks:
  - name: create content
    copy:
     content: "Hello World From SJSU - VM2"
     dest: /var/www/html/index.html
- hosts: vm3
  become: true
  tasks:
  - name: create content
    copy:
     content: "Hello World From SJSU - VM3"
     dest: /var/www/html/index.html
